export const meta = {
  name: 'kicadfp-gui',
  description: 'Графический интерфейс kicadfp на PySide6: документ/undo, канва, таблицы, главное окно, тесты offscreen, ревью',
  phases: [
    { title: 'GUI-Core', detail: 'document, commands, app' },
    { title: 'GUI-Widgets', detail: 'канва, таблицы/панели, дерево/диалоги параллельно' },
    { title: 'GUI-Main', detail: 'главное окно, интеграция, сценарий 8' },
    { title: 'GUI-Review', detail: 'ревью + исправления' },
  ],
}

const REPO = (typeof args === 'object' && args && args.repo) || '/Users/juli/Desktop/Claude/kicadfp'  // передайте args: {repo: '<путь к репозиторию>'}
const PY = REPO + '/.venv/bin/python'
const SCRATCH = REPO + '/.cache/scratch'

const COMMON = `
Проект: kicadfp — библиотека и редактор файлов посадочных мест KiCad на Python. Репозиторий ${REPO}, Python ${PY} (venv 3.12, PySide6 6.11, pytest, pytest-qt). Тесты: cd ${REPO} && QT_QPA_PLATFORM=offscreen ${PY} -m pytest -q tests/.
Ядро готово и протестировано: kicadfp/sexpr.py, format_rules.py, layers.py (COLORS, DRAW_ORDER, имена слоёв), geometry.py, model.py (Footprint/Pad/Drill/Line/Rect/Circle/Arc/Poly/Curve/Text/Model — представления над деревом; см. docstrings и tests/test_model_*.py), io.py (load/save/dumps), validate.py (validate -> список Issue), generators/ (GENERATORS реестр, describe(name)), library.py (Library), render.py (render_svg/save_png), cli.py. ОБЯЗАТЕЛЬНО прочитай ${REPO}/docs/dev/architecture.md (§14 — контракт GUI) и код model.py/document API перед работой; используй ИМЕННО существующий API модели (не дублируй модель).
Правила: пакет kicadfp/gui/ — единственное место с зависимостью от PySide6; импорт PySide6 только внутри kicadfp/gui/*. Идентификаторы английские, docstrings/комментарии/надписи интерфейса — русские. Все изменения модели ТОЛЬКО через FootprintDocument.apply(QUndoCommand) (отмена/повтор ≥ 100 шагов, QUndoStack.setUndoLimit(1000)), после каждой команды документ испускает changed(); таблицы, панели и канва перерисовываются по этому сигналу и не хранят копий данных модели (ключ элемента — id(view.node) / сам объект-представление, равенство по узлу). Не блокируй GUI модальными окнами в тестах: диалоги должны иметь методы для программного заполнения. Тесты — pytest-qt (фикстура qtbot) с QT_QPA_PLATFORM=offscreen, маркер @pytest.mark.gui, файлы tests/test_gui_*.py. Не запускай git commit. Не редактируй файлы вне своей зоны (список в задаче); если нужен фикс в ядре — минимальный, с описанием в ответе.
Финальный ответ — краткое резюме: что сделано, API, известные ограничения.
`

const REVIEW_SCHEMA = {
  type: 'object',
  properties: {
    findings: { type: 'array', items: { type: 'object', properties: {
      severity: { type: 'string', enum: ['high', 'medium', 'low'] }, file: { type: 'string' }, line: { type: 'integer' },
      summary: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } },
      required: ['severity', 'file', 'summary', 'evidence', 'fix'] } },
    tests_pass: { type: 'boolean' }, notes: { type: 'string' },
  },
  required: ['findings', 'tests_pass'],
}

phase('GUI-Core')
const core = await agent(COMMON + `
ЗАДАЧА: основа GUI — kicadfp/gui/__init__.py (main(argv=None) -> int: создаёт QApplication при необходимости, MainWindow (импорт отложенный: класс появится позже — импортируй внутри main через try/except ImportError и выведи понятное сообщение), открывает путь из argv, exec), kicadfp/gui/app.py (create_app(), общие настройки, русская локализация стандартных кнопок через QLocale, палитра), kicadfp/gui/document.py — FootprintDocument(QObject): свойства fp (Footprint|None), path (Path|None), library (Library|None, если открыт из .pretty), undo_stack (QUndoStack, undoLimit 1000), is_modified; сигналы changed() (после любой команды/undo/redo/открытия), selection_changed(object) (выделенный элемент модели или None), modified_changed(bool), document_changed() (открыт другой корпус); методы open(path), open_footprint(fp, path=None), new_footprint(name), save(strict=False) -> bool, save_as(path), apply(cmd: QUndoCommand), select(item), selected, close() -> bool (запрос подтверждения делегируется вызывающему через свойство confirm_discard: Callable[[], bool], по умолчанию всегда True — MainWindow подставит QMessageBox); kicadfp/gui/commands.py — SetAttrCommand(doc, view, attr, new_value, text=None, merge_id=None) с mergeWith для перетаскивания (одинаковые view+attr → слияние, хранит первое old), SetAttrsCommand (несколько атрибутов одного view, напр. x и y одновременно), AddItemCommand(doc, item_view_or_node) / RemoveItemCommand(doc, item) — снимок узла и индекса в корне для точного восстановления позиции, ReplaceNodeCommand(doc, before_copy, after_copy) для сложных операций (move/rotate/flip/renumber/generator) — применяет копию узла в корень (root.items = copy) с сохранением идентичности корневого Node, BatchCommand(children). Каждый command после redo/undo вызывает doc._emit_changed(). Тесты tests/test_gui_document.py: открыть DIP-14 (kicad8), SetAttrCommand на pad.x → dumps меняется в одном месте, undo возвращает байт-в-байт исходный текст, redo, 150 команд подряд и 150 undo (лимит ≥ 100), merge при перетаскивании (10 SetAttr с merge_id → 1 шаг undo), Add/Remove pad с восстановлением позиции в файле, ReplaceNodeCommand с fp.move, is_modified/сигналы (qtbot.waitSignal), save в tmp, close с confirm_discard=False → False.
Можно менять: kicadfp/gui/__init__.py, app.py, document.py, commands.py, tests/test_gui_document.py.`,
  { label: 'gui:core', phase: 'GUI-Core', effort: 'max', model: 'opus' })

phase('GUI-Widgets')
const WIDGETS = [
  { key: 'canvas', files: ['kicadfp/gui/canvas.py', 'tests/test_gui_canvas.py'], prompt: `
ЗАДАЧА: kicadfp/gui/canvas.py — PreviewCanvas(QGraphicsView) для FootprintDocument: сцена в мм (1 единица сцены = 1 мм, ось Y вниз как в KiCad; масштаб через QTransform), фон и сетка (шаг из списка 1.25/1.0/0.5/0.25/0.1 мм, свойство grid, подписи не нужны, отдельные линии для осей через начало), отрисовка ВСЕХ элементов модели в цветах kicadfp.layers.COLORS по порядку DRAW_ORDER с прозрачностью для меди: площадки (thru_hole: медь цветом pad_th + отверстие; smd/connect: цвет слоя; np_thru_hole: только отверстие + контур; формы circle/rect/oval/roundrect/trapezoid/custom(anchor+primitives упрощённо), поворот, номер площадки текстом внутри), графика (line/rect/circle/arc через QPainterPath (arcTo по geometry) /poly/curve; ширина = width; fill), тексты (QGraphicsSimpleTextItem или свой item: размер шрифта по font_size_y, mirror/justify/угол, hide → не рисовать, но опция показать скрытые), модели не рисуются; фильтр видимости слоёв (set_layer_visible); зум колесом к курсору, «вписать» (fit), панорамирование средней кнопкой и перетаскиванием с зажатым пробелом; выбор элемента щелчком (hit-test по QGraphicsItem.data(0) = представление модели) с подсветкой (цвет selection) и doc.select(item); перетаскивание выбранной площадки/графики/текста левой кнопкой — во время drag обновляется временная позиция, по отпусканию одна команда (SetAttrsCommand x/y, для графики — ReplaceNodeCommand с move(dx,dy) элемента); привязка к сетке при перетаскивании (свойство snap); сигнал cursor_moved(x, y) для статусной строки; перестроение сцены по doc.changed() с сохранением выделения и вида. Тесты tests/test_gui_canvas.py (qtbot, offscreen): число графических элементов для DIP-14 (14 площадок + графика), цвет/слой, выбор щелчком по координатам сцены (QTest.mouseClick через mapFromScene), перетаскивание площадки (mousePress/Move/Release) → в модели изменились x/y и это одна команда undo; сохранение видимости слоёв; grab() в QImage не падает и содержит нефоновые пиксели.` },
  { key: 'tables', files: ['kicadfp/gui/pad_table.py', 'kicadfp/gui/items_table.py', 'kicadfp/gui/props_panel.py', 'tests/test_gui_tables.py'], prompt: `
ЗАДАЧА: (1) kicadfp/gui/pad_table.py — PadTableModel(QAbstractTableModel) над doc.fp.pads: столбцы «№», «Тип» (combo delegate из PAD_TYPES), «Форма» (combo из PAD_SHAPES), «X», «Y», «Поворот», «Размер X», «Размер Y», «Отверстие» (диаметр; пусто = нет; для овала «w x h»), «Слои» (строка через запятую; delegate с выпадающим списком пресетов + свободный ввод); setData → SetAttrCommand/SetAttrsCommand через doc.apply (валидация ввода: числа float, недопустимое → отклонить и вернуть False); PadTable(QTableView) с сортировкой выкл., выбор строки → doc.select(pad), doc.selection_changed → выделение строки; контекстное меню: добавить площадку, удалить, дублировать, групповые операции… (сигнал batch_requested). (2) kicadfp/gui/items_table.py — ItemsTableModel над fp.graphics + fp.texts: «Тип» (line/rect/circle/arc/poly/curve/text:reference/…), «Слой» (combo из ALL_LAYERS), «Ширина/Размер» (width или font_size), «X1/X», «Y1/Y», «X2», «Y2» (для circle: центр и радиус; arc: start/end; poly: первая точка и число точек — только чтение), «Текст» (для текстов, редактируемый), «Скрыт» (checkbox для текстов); редактирование → команды; выбор → doc.select. (3) kicadfp/gui/props_panel.py — PropertiesPanel(QWidget) (QFormLayout): имя, слой (F.Cu/B.Cu), описание (descr), ключевые слова (tags), атрибуты (чекбоксы smd/through_hole/board_only/exclude_from_pos_files/exclude_from_bom/allow_missing_courtyard/dnp), clearance/solder_mask_margin/solder_paste_margin/solder_paste_ratio (QLineEdit, пусто = нет), zone_connect (combo: наследовать/0/1/2/3), версия и uuid (только чтение); изменения применяются по editingFinished через команды; обновление из doc.changed() без рекурсии (блокировать сигналы). Все виджеты берут документ в конструкторе и подписываются на doc.changed/document_changed/selection_changed. Тесты tests/test_gui_tables.py: rowCount/columnCount для DIP-14, data() значений площадки 1, setData X → модель изменилась и undo работает, недопустимый ввод отклонён, смена типа/формы через setData, PropertiesPanel: ввод descr → fp.descr, чекбокс attr → fp.attrs, ItemsTable: изменение слоя графики и текста.` },
  { key: 'tree-dialogs', files: ['kicadfp/gui/libtree.py', 'kicadfp/gui/dialogs.py', 'tests/test_gui_dialogs.py'], prompt: `
ЗАДАЧА: (1) kicadfp/gui/libtree.py — LibraryTree(QTreeView) с QStandardItemModel: корни — открытые библиотеки .pretty (kicadfp.library.Library) и одиночные файлы; дети — имена корпусов (иконки не обязательны); методы add_library(path), add_file(path), remove_selected(), refresh(); двойной щелчок/Enter → сигнал open_requested(path: Path); контекстное меню: открыть, переименовать (QInputDialog → Library.rename), удалить (подтверждение), копировать в другую библиотеку (выбор из открытых + новое имя → Library.copy_to), обновить; сигнал libraries_changed. (2) kicadfp/gui/dialogs.py: GenerateDialog(QDialog) — выпадающий список генераторов из kicadfp.generators.GENERATORS с русскими названиями, форма параметров, построенная по generators.describe(name) (float → QDoubleSpinBox с 3 знаками, int → QSpinBox, bool → QCheckBox, str → QLineEdit, списки/кортежи (mounting_holes) → QLineEdit с текстом JSON), поле имени; метод build() -> Footprint (вызывает генератор); ошибки параметров показываются в QLabel, не исключением; программный API: set_generator(name), set_param(name, value). ValidateDialog(QDialog, немодальный) — таблица замечаний (уровень с цветом, код, сообщение), кнопки «Проверить снова», двойной щелчок → doc.select(issue.element); метод run(). PadBatchDialog(QDialog) — групповые операции над выбранными/всеми площадками: перенумерация (правило: последовательно с N, по X/Y/файлу; префикс), сдвиг dx/dy, поворот на угол вокруг точки, смена слоёв (пресет/строка), общий размер (size X/Y), общее отверстие, тип/форма; метод apply_to(doc, pads) — одна ReplaceNodeCommand/BatchCommand (один шаг undo). ItemPropertiesDialog — свойства выбранного элемента (pad/graphic/text) в форме (все редактируемые атрибуты представления, по типу) → одна команда. AboutDialog с версией. Тесты tests/test_gui_dialogs.py: GenerateDialog для dip: set_param('pins', 14) → build() даёт 14 площадок; для lab_snp8 без параметров; PadBatchDialog.apply_to: перенумерация/сдвиг/смена слоёв на DIP-14 меняют модель, один undo возвращает всё; ValidateDialog.run на корпусе с drill > size показывает ошибку; LibraryTree: add_library(kicad8/Package_DIP.pretty) → 281 ребёнок, rename/copy через Library в tmp-каталоге.` },
]
const widgets = await parallel(WIDGETS.map(w => () =>
  agent(COMMON + `\nГотовая основа GUI (прочитай!): kicadfp/gui/document.py (FootprintDocument), kicadfp/gui/commands.py. Можно менять только: ${w.files.join(', ')} (создать).` + w.prompt,
    { label: 'gui:' + w.key, phase: 'GUI-Widgets', effort: 'high', model: 'opus' }).then(r => ({ key: w.key, result: String(r).slice(0, 2000) }))
))

phase('GUI-Main')
const main = await agent(COMMON + `
${(args && args.main_note) || ''}
ЗАДАЧА: kicadfp/gui/mainwindow.py — MainWindow(QMainWindow), собирающее готовые компоненты (прочитай их код: document.py, commands.py, canvas.py, pad_table.py, items_table.py, props_panel.py, libtree.py, dialogs.py): центр — PreviewCanvas; док-панели (QDockWidget): «Библиотеки» (LibraryTree, слева), «Свойства корпуса» (PropertiesPanel, справа), «Площадки» (PadTable, снизу), «Графика и тексты» (ItemsTable, снизу, вкладкой рядом), «Слои» (список чекбоксов видимости слоёв с цветными квадратиками). Меню: Файл (Создать корпус…, Открыть файл…, Открыть библиотеку…, Сохранить Ctrl+S, Сохранить как…, Экспорт SVG…, Экспорт PNG…, недавние файлы (QSettings), Выход), Правка (Отменить Ctrl+Z / Повторить Ctrl+Shift+Z через undo_stack.createUndoAction/createRedoAction, Удалить Del, Свойства элемента… Enter/двойной щелчок, Групповые операции над площадками…, Добавить площадку/линию/прямоугольник/окружность/текст — с параметрами по умолчанию в центре вида), Корпус (Проверить F7 → ValidateDialog, Создать типовой корпус… → GenerateDialog → новый документ, Сдвинуть…, Повернуть…, Отразить, Перенумеровать площадки…), Вид (Вписать F, Увеличить/Уменьшить, Сетка (подменю шагов), Привязка к сетке, Показывать скрытые тексты), Справка (О программе). Панель инструментов с основными действиями. Статусная строка: координаты курсора (мм), имя файла, «изменён». Заголовок окна: «kicadfp — имя [*]» с setWindowModified. Закрытие окна/открытие другого при несохранённых изменениях — QMessageBox (Сохранить/Не сохранять/Отмена) через doc.confirm_discard. Ошибки открытия (SexprSyntaxError) — QMessageBox с текстом «строка N, позиция M». Настройки окна (геометрия, доки) в QSettings. Обнови kicadfp/gui/__init__.py main() (импорт MainWindow) и cli.py команду gui (если нужно). Тесты tests/test_gui_mainwindow.py (offscreen): создание окна, открытие DIP-14 kicad8 → таблицы заполнены, сценарий 8 ТЗ: перетащить площадку на канве (QTest mouse events) и изменить X в таблице → значения в таблице и на канве совпадают, Отменить, Повторить, Сохранить в tmp → файл содержит итоговые координаты (парсим и проверяем pad); генерация dip через диалог программно → новый документ с 14 площадками; закрытие с несохранёнными → confirm вызывается (подмени doc.confirm_discard). Сделай также tests/gui_screenshots.py (не тест; скрипт: открывает DIP-14, grab() окна в docs/img/gui_main.png — при offscreen; вызови его один раз, чтобы картинка появилась).
Можно менять: kicadfp/gui/mainwindow.py, kicadfp/gui/__init__.py, kicadfp/cli.py (только команда gui), tests/test_gui_mainwindow.py, tests/gui_screenshots.py, docs/img/*. Минимальные правки в других gui-модулях допустимы для интеграции (с описанием).`,
  { label: 'gui:main', phase: 'GUI-Main', effort: 'max', model: 'opus' })

phase('GUI-Review')
const lenses = ['корректность взаимодействия модель↔GUI, undo/redo, сохранение без потерь', 'удобство/ошибки интерфейса: сценарии пользователя из ТЗ 4.1.8 и Г.8, падения, утечки сигналов, кросс-платформенность']
const reviews = (await parallel(lenses.map((lens, i) => () => agent(COMMON + `
РОЛЬ: adversarial-ревьюер GUI (линза: ${lens}). Прочитай kicadfp/gui/*.py и tests/test_gui_*.py, запусти тесты (QT_QPA_PLATFORM=offscreen), напиши свои сценарии в ${SCRATCH}/review-gui/ (создай): открыть каждый файл из tests/fixtures/kicad8/Package_SO.pretty (первые 30) и kicad6/kicad5 — ни один не должен падать при отрисовке/заполнении таблиц; изменить каждую ячейку таблицы площадок на допустимое значение → сохранённый файл отличается ровно этим токеном; undo до начала → байт-в-байт исходный; 120 команд и полный откат; удаление элемента и undo восстанавливает позицию в файле; закрытие с несохранённым; GenerateDialog для каждого генератора из GENERATORS с умолчаниями. Ищи РЕАЛЬНЫЕ дефекты; каждое утверждение — с воспроизводимым доказательством. Ничего не исправляй. Верни findings.`,
  { label: `gui:review:${i + 1}`, phase: 'GUI-Review', schema: REVIEW_SCHEMA, effort: 'high', model: 'opus' })))).filter(Boolean)
const findings = reviews.flatMap(r => r.findings || []).filter(f => f.severity !== 'low')
log(`GUI: ${findings.length} замечаний`)
let fix = null
if (findings.length) {
  fix = await agent(COMMON + `
РОЛЬ: исправитель GUI. Для каждого замечания ниже: воспроизведи, исправь (в kicadfp/gui/*.py, при необходимости минимально в ядре), добавь регрессионный тест; ошибочные — отклони с доказательством. Прогони все тесты (QT_QPA_PLATFORM=offscreen ${PY} -m pytest -q). Отчёт по каждому пункту.
ЗАМЕЧАНИЯ: ${JSON.stringify(findings, null, 1)}`, { label: 'gui:fix', phase: 'GUI-Review', effort: 'high', model: 'opus' })
}
return { core: String(core).slice(0, 2000), widgets, main: String(main).slice(0, 2000), findings: findings.length, fix: fix && String(fix).slice(0, 3000) }
