export const meta = {
  name: 'kicadfp-understand',
  description: 'Исследование форматов KiCad (6-10) и legacy .mod, подготовка точных спецификаций для реализации kicadfp',
  phases: [
    { title: 'Research', detail: '6 параллельных исследователей, каждый пишет спецификацию в docs/dev' },
    { title: 'Critique', detail: 'критик полноты: что упущено' },
  ],
}

const KSRC = REPO + '/refs/kicad-src'
const KFP = REPO + '/.cache/kfp'
const REPO = (typeof args === 'object' && args && args.repo) || '/Users/juli/Desktop/Claude/kicadfp'  // передайте args: {repo: '<путь к репозиторию>'}
const FIX = REPO + '/tests/fixtures'
const REF = REPO + '/refs/kicad-2011-gen'
const BZR = REPO + '/refs/bzr2986'
const PY = REPO + '/.venv/bin/python'
const SCRATCH = REPO + '/.cache/scratch'

const COMMON = `
Ты — исследователь формата файлов KiCad для проекта kicadfp (библиотека и редактор файлов посадочных мест .kicad_mod на Python 3.10+, ядро без сторонних зависимостей). Твоя задача — написать ТОЧНУЮ спецификацию (Markdown, на русском языке, токены/идентификаторы/код на английском), по которой другой инженер реализует код без доступа к исходникам KiCad. Никаких догадок: каждое утверждение подтверждай ссылкой на файл:строку исходников KiCad или на конкретный файл-фикстуру. Где неизвестно — так и пиши «не проверено».

Материалы (только чтение, ничего в них не менять):
- Исходники KiCad (скачаны с gitlab): ${KSRC}/{6.0,7.0,8.0,9.0,master}/ — имена файлов = путь в репозитории с '/' заменённым на '_'. Есть: kicad_io_utils.cpp (Prettify, 8.0/9.0/master), pcb_io_kicad_sexpr.cpp (writer 8.0/9.0/master), pcb_io_kicad_sexpr_parser.cpp (parser 8.0/9.0/master), pcb_io_kicad_sexpr.h (версии формата 9.0), eda_units.cpp (форматирование чисел 7.0/8.0/9.0), richio.cpp (Quotes/экранирование 9.0), layer_id.cpp + layer_ids.h (имена слоёв 6.0..9.0), pcb.keywords (9.0), pcb_io_kicad_legacy.cpp/.h (чтение старого формата .mod/.brd, 9.0), pcb_plugin.cpp + pcb_parser.cpp (writer/parser 6.0 и 7.0), legacy_plugin.cpp (6.0/7.0), base_units.cpp (6.0). Если нужен ещё какой-то файл исходников — скачай его сам: curl -sL "https://gitlab.com/kicad/code/kicad/-/raw/<branch>/<path>" -o ${SCRATCH}/kicad-src/<branch>/<path с _> (сеть доступна).
- Реальные файлы стандартных библиотек KiCad (sparse-клоны kicad-footprints): ${KFP}/v6.0.0 (внимание: это формат KiCad 5, корень "module"), ${KFP}/v7.0.0 (формат KiCad 6, version 20211014), ${KFP}/v8.0.0 (version 20240108, KiCad 8), ${KFP}/v9.0.0 (KiCad 9), ${KFP}/master (KiCad 10-dev, version 20260206). Кураторские подмножества тех же файлов лежат в репозитории: ${FIX}/{kicad5,kicad6,kicad8,kicad9,kicad10dev}/*.pretty/*.kicad_mod и старый формат ${FIX}/legacy_mod/My_lib.mod.
- Справочный проект по старому формату (KiCad 2011): ${REF} (docs/pcbnew-mod-format.md, docs/pcbnew-pad-format.md, kicadgen/mod.py, kicadgen/gen_footprints.py, examples/), и снапшот исходников KiCad 2011: ${BZR}.
- Python для скриптов: ${PY} (3.12). Временные скрипты клади в ${SCRATCH}/research/ (создай каталог), НЕ в репозиторий.


ВАЖНО — уже есть наработки предыдущего (прерванного) прогона в ${SCRATCH}/research/: prettify.py (порт Prettify 8.0/9.0/master с проверкой байт-в-байт), layout67.py (табличная раскладка KiCad 6/7), inventory.py + inventory_kfp.json + inventory_fixtures.json (инвентаризация токенов; итог уже скопирован в ${REPO}/docs/dev/token-inventory.json), legacy_expected.py/.out (ожидаемая конвертация My_lib.mod), gen_layers_json.py (уже создал ${REPO}/docs/dev/layers.json), scan_layers*.py, numfmt_check.py, order_check.py, каталоги gen/ и klc/ (материалы по генераторам и KLC). Сначала посмотри, что из этого относится к твоей задаче, ПРОВЕРЬ (запусти) и переиспользуй — не делай ту же работу заново; документ .md в docs/dev нужно написать в любом случае (его ещё нет).

Правила: пиши результат в указанный файл в ${REPO}/docs/dev/ (создай при необходимости). Не трогай другие файлы репозитория. Документ должен быть самодостаточным, с таблицами, точными форматами (какие токены, в каком порядке, при каком условии пишутся, с какими аргументами, кавычки или нет), примерами из реальных файлов. В конце документа — раздел «Проверено» со списком того, что ты проверил скриптом на фикстурах (с числами), и раздел «Открытые вопросы». Финальный ответ (return value) — краткое резюме (10-20 строк): что написано, ключевые находки, что не удалось проверить.
`

const TASKS = [
  {
    key: 'writer',
    file: 'format-writer.md',
    prompt: `
ЗАДАЧА: docs/dev/format-writer.md — «Порядок и условия записи токенов writer'ом KiCad» для файлов .kicad_mod.
Для KiCad 9.0 (основной, файл ${KSRC}/9.0/pcbnew_pcb_io_kicad_sexpr_pcb_io_kicad_sexpr.cpp) и отличий в 8.0, 7.0, 6.0 (и master) задокументируй ТОЧНО (в порядке вывода, с условиями «пишется если …», с формой аргументов и с указанием, что в кавычках (Quotew/Quotes) а что голый символ):
1. Корневой узел footprint: format(const FOOTPRINT*) — все дочерние токены по порядку (version, generator, generator_version, locked, placed, layer, uuid, at, descr, tags, property-поля, component_classes, ki_fp_filters, path, sheetname, sheetfile, solder_mask_margin, solder_paste_margin, solder_paste_margin_ratio (в 6/7 — solder_paste_ratio?), clearance, zone_connect, attr (все флаги и их порядок), private_layers, net_tie_pad_groups, затем графика, pads, zones, groups, embedded_fonts, model). Как сортируются pads/drawings/zones при записи (cmp_pads, cmp_drawings — найди определения в footprint.cpp/.h, скачай если нужно) — нам это нужно знать, хотя мы сохраняем исходный порядок.
2. Текст: format(const PCB_FIELD*)/format(const PCB_TEXT*)/formatText-подобные функции: property "Name" "Value" (at x y angle) (unlocked yes) (layer ...) (hide yes) (uuid) (effects (font (face) (size) (thickness) (bold yes) (italic yes) (line_spacing)) (justify left/right top/bottom mirror)) (render_cache ...). Для fp_text в 6/7: (fp_text reference "REF**" (at x y [angle] [unlocked]) (layer "F.SilkS") [hide] (effects ...) (tstamp ...)). Условия: когда пишется угол в at, когда unlocked, когда hide, формы hide (голый vs (hide yes)), knockout, mirror.
3. Графика PCB_SHAPE: fp_line/fp_rect/fp_circle/fp_arc/fp_poly/fp_curve — координаты (start/end/center/mid/pts (xy) / bezier pts), stroke (width, type) vs width (6.0), fill (формы: (fill none|solid) в 6/7; (fill yes|no) в 8/9?; проверь по фикстурам!), layer, locked (форма), net, solder_mask_margin, uuid/tstamp. Правила formatPolyPts.
4. PAD: полный порядок для 9.0 (уже известен из исходника — задокументируй) и отличия 8.0/7.0/6.0 (например remove_unused_layers/keep_end_layers формы: в 8.0 «(remove_unused_layers no)»? в 7.0 голые токены remove_unused_layers/keep_end_layers?; tenting; padstack; teardrops; thermal_bridge_angle; die_length; property pad_prop_*; chamfer; options/primitives/anchor; net; pinfunction/pintype; drill формы).
5. model: путь, hide, opacity, offset/scale/rotate (xyz), в 6.0 — at vs offset.
6. zone и group внутри footprint (структуру задокументируй кратко, т.к. мы их только сохраняем).
7. formatLayer/formatLayers: как выводится (layer "X") и (layers ...) — в каких версиях в кавычках; алгоритм свёртки в *.Cu, F&B.Cu, *.Mask, *.Paste и т.п. (LSET::FmtBin? formatLayers в 6.0/7.0/8.0/9.0), порядок слоёв в списке.
8. Форматирование чисел: FormatInternalUnits (int IU → mm), FormatAngle, FormatDouble2Str/Double2Str, opacity %0.4f; какой формат в Python даёт байт-в-байт тот же результат ('%.10g' и ветка малых чисел) — проверь на примерах (0.15, 1.6, 3.81, 0.000001, 12.3456789, -0.05, 1e-5, 100, 0.1+0.2).
9. Кавычки и экранирование строк: OUTPUTFORMATTER::Quotes/Quotew (richio.cpp 9.0): какие символы экранируются и как (\\", \\\\, \\n, \\r, \\t? другие?), unescape в парсере (DSNLEXER: dsnlexer.cpp — скачай common/dsnlexer.cpp 9.0 и опиши разбор строк в кавычках, эскейпы, что считается символом (bare token), какие символы допустимы в bare token, как разбираются числа).
10. Булевы значения: FormatBool (yes/no) в 8/9 и голые флаги в 6/7; список всех токенов, где форма различается по версиям.
11. Табличка «версия формата → что пишет KiCad»: 20211014 (6.0), 20221018 (7.0), 20240108 (8.0), 20241229 (9.0), 20260206 (10-dev) — какие токены появились/исчезли (tedit, tstamp→uuid, width→stroke, fp_text→property, generator_version, embedded_fonts, point, duplicate_pad_numbers_are_jumpers, ...). Используй комментарии в pcb_io_kicad_sexpr.h.
Проверь ключевые утверждения grep'ом по фикстурам (например: встречается ли в v8 файлах «(hide yes)» и голый «hide»; «(fill yes)» vs «(fill solid)»; кавычки в layers).`,
  },
  {
    key: 'legacy-layout',
    file: 'format-layout.md',
    prompt: `
ЗАДАЧА: docs/dev/format-layout.md — «Раскладка пробелов/переводов строк (whitespace layout) файлов .kicad_mod по версиям» — чтобы наш форматтер выдавал БАЙТ-В-БАЙТ то же, что KiCad, для неизменённого дерева.
A. KiCad 8/9/10: алгоритм KICAD_FORMAT::Prettify (${KSRC}/8.0 и 9.0 и master kicad_io_utils.cpp). Опиши алгоритм построчно так, чтобы его можно было портировать на Python 1:1 (состояния listDepth, lastNonWhitespace, inQuote, hasInsertedSpace, inMultiLineList, inXY, inShortForm/shortFormDepth, column, backslashCount; константы 99 и 72; особый случай xy; что такое aCompactSave и включён ли он по умолчанию — найди ADVANCED_CFG m_CompactSave default; отличия master (FORMAT_MODE)). Опиши, как выглядит вход Prettify: writer печатает токены через OUTPUTFORMATTER::Print без переводов строк? (найди в richio.cpp 9.0 как STRING_FORMATTER/PRETTIFIED_FILE_OUTPUTFORMATTER буферизует и где вызывается Prettify; какие пробелы вставляет Print между «(» и токенами — например m_out->Print("(at %s %s)") при пустом угле даёт «(at 1 2 )»? Prettify это убирает — покажи как). Напиши на Python (в ${SCRATCH}/research/prettify.py) порт алгоритма + минимальный токенизатор/сериализатор и ПРОВЕРЬ: для КАЖДОГО файла из ${KFP}/v8.0.0, v9.0.0, master (все .pretty) — parse → сериализация в одну строку → prettify → сравнение с исходными байтами. Цель 100% совпадение; приведи статистику (сколько файлов, сколько совпало), и для несовпавших — причину (первое расхождение). Порт скрипта включи в документ как приложение (полный код) — он станет основой реализации.
B. KiCad 6.0 и 7.0 writer (${KSRC}/6.0 и 7.0 pcbnew_plugins_kicad_pcb_plugin.cpp): там переводы строк и отступы вшиты в вызовы m_out->Print(aNestLevel, ...) с явными "\\n". Для файлов .kicad_mod (footprint) задокументируй раскладку для каждого типа узла: footprint (заголовок «(footprint "X" (version N) (generator pcbnew)» + «\\n», далее каждый дочерний с отступом 2 пробела на уровень), fp_text (многострочный: effects на новой строке, tstamp на новой строке, «)» на своей строке), fp_line/fp_rect/fp_circle/fp_arc (в одну строку), fp_poly/fp_curve (formatPolyPts: как переносятся точки — сколько на строке, отступы), pad (в одну строку; но с primitives — многострочно: как именно), model (многострочно: offset/scale/rotate каждый на своей строке), zone (многострочно), group, property (одна строка), attr, descr/tags. Отдельно: где ставятся два пробела в отступе, где закрывающая скобка на своей строке, есть ли пробел перед «)». Затем напиши Python-скрипт (${SCRATCH}/research/layout67.py) с табличным описанием раскладки (dict «имя узла → правила») и ПРОВЕРЬ на всех файлах ${KFP}/v7.0.0 (формат 6.0, version 20211014): parse → format по таблице → сравнение байт-в-байт. Приведи статистику и причины расхождений. Также проверь на ${KFP}/v6.0.0 (формат KiCad 5, «module»): там writer 5.1 — задокументируй отличия, если раскладка совпадает с 6.0 — отметь; если нет — опиши правила 5.x насколько это удаётся вывести из файлов (исходники 5.1 можно скачать: branch 5.1, pcbnew/kicad_plugin.cpp).
C. Итог: таблица «версия файла → стиль форматирования» и рекомендация, какой стиль применять при записи файла каждой версии и при создании новых файлов (по умолчанию 20241229 стиль 9.0).`,
  },
  {
    key: 'tokens',
    file: 'format-tokens.md',
    prompt: `
ЗАДАЧА: docs/dev/format-tokens.md + docs/dev/token-inventory.json — «Полный перечень токенов формата footprint, принимаемых парсером KiCad, и эмпирическая инвентаризация по реальным файлам».
Часть 1 (парсер 9.0: ${KSRC}/9.0/pcbnew_pcb_io_kicad_sexpr_pcb_io_kicad_sexpr_parser.cpp; сверь с 8.0 и master): для parseFOOTPRINT, parsePAD, parsePCB_SHAPE (fp_line/fp_rect/fp_circle/fp_arc/fp_poly/fp_curve), parsePCB_TEXT/parsePCB_FIELD/parseEDA_TEXT (effects/font/justify), parseFP_3DMODEL (model), parseZONE, parseGROUP, parseSTROKE/parseFill (T_fill формы), parseXY/parseOutlinePoints (pts с arc внутри), parseBoardItemLayer/parseBoardItemLayersAsMask (layers, *.Cu, F&B.Cu, ...), parseTEARDROP, parsePadstack, parsePCB_TEXTBOX/parsePCB_TABLE/parsePCB_DIMENSION/parsePCB_REFERENCE_IMAGE (только структура — сохраняем как есть), embedded_files. Для КАЖДОГО узла — таблица: токен, форма аргументов (типы: число/строка/символ/подузел), обязательность, версия появления, устаревшие формы, которые парсер всё ещё принимает (tedit, tstamp, width, angle в fp_arc, fp_text reference/value/user, голый hide/locked/unlocked, (fill none/solid/yes/no), (drill oval w h (offset x y)), net с именем, die_length, thermal_width/thermal_gap, autoplace_cost90/180, solder_paste_ratio vs solder_paste_margin_ratio, (at x y [angle] [unlocked]), property без текстовых атрибутов (6/7) vs с ними (8+), 'locked' как голый токен после имени слоя и т.п.). Отдельно: какие ошибки парсер выдаёт (Expecting ...), какие токены игнорируются молча (Unexpected?), что делает парсер с неизвестными токенами (это критично: наша Программа должна сохранять неизвестное — а KiCad при чтении неизвестного токена выдаёт ошибку? найди точно: в parseFOOTPRINT default: Expecting(...)? Тогда «неизвестный узел example_token» из ТЗ сценария 3 — KiCad его не прочитает; отметь это как риск для сценария приёмки и предложи формулировку).
Часть 2 (эмпирика): напиши скрипт ${SCRATCH}/research/inventory.py с минимальным S-expr парсером и пройди ВСЕ .kicad_mod из ${KFP}/v6.0.0, v7.0.0, v8.0.0, v9.0.0, master (по отдельности, это ~5-6 тысяч файлов). Собери: для каждого имени родительского узла → имена дочерних узлов с частотой и 2-3 примера сырых форм; голые символы-значения (pad type, shape, attr флаги, fill, stroke type, justify, hide формы, layers формы и кавычки); список версий (version), генераторов; все встречающиеся имена слоёв; редкие/неожиданные конструкции (zone, group, dimension, fp_text_box, image, embedded_fonts, point, duplicate_pad_numbers_are_jumpers, teardrops, tenting, padstack, net в библиотечных pad, property с эффектами и без, custom pads с primitives, chamfer, oval drill, offset). Сохрани полный JSON в ${REPO}/docs/dev/token-inventory.json (структурированный, по версиям) и краткую сводку (таблицы) в .md. Отдельно перечисли конструкции, встречающиеся в фикстурах репозитория ${FIX} (кураторское подмножество) — чтобы тесты можно было привязать к конкретным файлам (например: «custom pad с primitives: kicad8/Package_SO.pretty/XXX.kicad_mod»). Для каждого «интересного» токена дай путь к 1-2 файлам-примерам из ${FIX}.`,
  },
  {
    key: 'layers',
    file: 'layers.md',
    prompt: `
ЗАДАЧА: docs/dev/layers.md + docs/dev/layers.json — «Слои KiCad: канонические имена, групповые обозначения, старая нумерация, цвета».
1. Полный список канонических имён слоёв для KiCad 6, 7, 8, 9 (${KSRC}/*/common_layer_id.cpp: LayerName/LSET::Name, ${KSRC}/*/include_layer_ids.h enum PCB_LAYER_ID): F.Cu, In1.Cu…In30.Cu, B.Cu, B.Adhes, F.Adhes, B.Paste, F.Paste, B.SilkS, F.SilkS, B.Mask, F.Mask, Dwgs.User, Cmts.User, Eco1.User, Eco2.User, Edge.Cuts, Margin, B.CrtYd, F.CrtYd, B.Fab, F.Fab, User.1…User.9 (в 9.0 — до User.45? проверь по layer_ids.h 9.0 и парсеру), Rescue; какие из них допустимы для pad layers, для графики, для текста; какие «существуют» с точки зрения проверки «графика на несуществующем слое» (используй LSET::AllLayersMask / парсер: что он делает с неизвестным именем слоя — ошибка? (проверь parseBoardItemLayer в 9.0)).
2. Групповые обозначения в (layers ...) у pad: *.Cu, F&B.Cu, *.Mask, *.Paste, *.SilkS, *.Adhes, *.CrtYd, *.Fab, *.Eco? — точный список, который принимает парсер (parseBoardItemLayersAsMask, 6.0–9.0) и который пишет writer (formatLayers), с правилами свёртки. Пресеты слоёв для типов площадок (что KiCad ставит по умолчанию для thru_hole/smd/connect/np_thru_hole — найди в pad.cpp/pad.h: PAD::PTHMask(), SMDMask(), ConnSMDMask(), UnplatedHoleMask(), ApertureMask(); скачай pcbnew/pad.cpp 9.0 при необходимости).
3. Старая нумерация слоёв KiCad ≤5 (legacy .mod/.brd): номер 0..31 → современное имя (${KSRC}/9.0/pcbnew_pcb_io_kicad_legacy_pcb_io_kicad_legacy.cpp: leg_layer2new, leg_mask2new; и ${REF}/docs/pcbnew-mod-format.md §1.1), маска битов 0x1FFFFFFF → список слоёв; что KiCad делает с маской пада 00E0FFFF (STD) → (layers *.Cu *.Mask)?? — точно по коду legacy plugin (какие биты выкидываются, например SilkS у сквозных падов).
4. Цвета слоёв KiCad по умолчанию (тема «KiCad Default» / «KiCad Classic»): скачай ${'https://gitlab.com/kicad/code/kicad/-/raw/9.0/common/settings/color_settings.cpp'} и/или include/settings/color_settings.h, и найди default-значения COLOR4D для каждого слоя (LAYER_PADS_TH, LAYER_PAD_PLATEDHOLES, LAYER_NON_PLATEDHOLES, LAYER_PCB_BACKGROUND, LAYER_GRID, LAYER_SELECT_OVERLAY, LAYER_ANCHOR, F.Cu, B.Cu, In*.Cu, F.SilkS, B.SilkS, F.Mask, B.Mask, F.Paste, B.Paste, F.Fab, B.Fab, F.CrtYd, B.CrtYd, Edge.Cuts, Margin, Dwgs/Cmts/Eco1/Eco2, User.N). Дай RGB(A) в hex. Плюс порядок отрисовки слоёв (какой сверху) — из layer_ids.h/GetDefaultLayerOrder или pcb_painter/ pcb_view (можно скачать pcbnew/pcb_view.cpp или pcb_display_options; если сложно — предложи разумный порядок: F.Cu снизу … F.SilkS, F.Fab, F.CrtYd, Edge.Cuts сверху и пометь «предложение»).
5. layers.json: {"canonical": {"6.0": [...], "7.0": [...], "8.0": [...], "9.0": [...]}, "copper": [...], "wildcards": {"*.Cu": [...], ...}, "pad_presets": {"thru_hole": [...], "smd": [...], "smd_back": [...], "connect": [...], "np_thru_hole": [...]}, "legacy_index": {"0": "B.Cu", ...}, "legacy_mask_bits": {...}, "colors": {"F.Cu": "#C83434", ...}, "draw_order": [...]}.`,
  },
  {
    key: 'legacy-mod',
    file: 'legacy-mod.md',
    prompt: `
ЗАДАЧА: docs/dev/legacy-mod.md — «Преобразование библиотек старого формата PCBNEW-LibModule-V1 (.mod/.emp) в современную модель footprint» — спецификация конвертера.
Источники: ${REF}/docs/pcbnew-mod-format.md, ${REF}/docs/pcbnew-pad-format.md, ${REF}/kicadgen/mod.py (реализация записи/чтения старого формата), ${BZR}/pcbnew/class_module.cpp, class_pad.cpp, class_text_mod.cpp, class_edge_mod.cpp (writer 2011), и главное — как СОВРЕМЕННЫЙ KiCad читает этот формат: ${KSRC}/9.0/pcbnew_pcb_io_kicad_legacy_pcb_io_kicad_legacy.cpp (+ .h): функции FootprintEnumerate/FootprintLoad/cacheLib (LP_CACHE::Load, ReadAndVerifyHeader, SkipIndex, LoadModules), loadFOOTPRINT (loadMODULE), loadPAD, loadMODULE_TEXT, loadMODULE_EDGE, load3D, biuParse/degParse, m_conversion units: заголовок «PCBNEW-LibModule-V1» и «Units mm»/«Units deci-mils» — как определяется масштаб (deci-mils: 1 ед. = 0.00254 мм? проверь константы), округление в IU (нанометры) → мм с 6 знаками; обработка ориентации модуля и координат (Po, T*, D*, Pad Po — относительные при ориентации 0), Cd → descr, Kw → tags, At SMD/VIRTUAL → attr (smd / exclude_from_bom? board_only?), .SolderMask/.SolderPaste/.SolderPasteRatio/.LocalClearance → solder_mask_margin/solder_paste_margin/solder_paste_margin_ratio/clearance, Op → autoplace_cost90/180 (пишутся ли они в 9.0?), Sc/AR/Li, $SHAPE3D Na/Sc/Of/Ro → model (единицы смещения: в старом формате Of в дюймах? найди в load3D и в writer 9.0 как хранится m_Offset (мм) — и учти «Save 3D model offset in mm, instead of inches» 20171114), T0/T1/T2 → property Reference/Value или fp_text user: поля (X Y, размер Y X — порядок!, ориентация в 0.1°, толщина, M зеркало → justify mirror, I невидимый → hide, слой (0→20, 15→21 и т.д.), курсив, текст в кавычках с эскейпами), DS/DC/DA/DP → fp_line/fp_circle/fp_arc/fp_poly: единицы, толщина (width → stroke), слой; для DA: старое представление (центр, точка начала, угол 0.1°) → современное (start, mid, end) — точная формула с учётом знака угла и оси Y вниз (как делает legacy plugin: SetCenter/SetStart/SetArcAngleAndEnd — проверь знак: положительный угол = по часовой на экране?), $PAD: Sh (имя ≤4 символа, форма C/R/O/T, размеры, delta, ориентация 0.1°), Dr (сверло, offset, O w h овал), At (STD/SMD/CONN/HOLE + маска слоёв hex) → тип thru_hole/smd/connect/np_thru_hole + layers (алгоритм маски → список слоёв: leg_mask2new + какие слои отбрасываются; проверь для 00E0FFFF, 00808000, 00888000, 00E00001), Ne (номер, имя цепи — в библиотеке игнорируем), Po. Также: несколько модулей в файле, $INDEX, комментарии «#», кодировка, CRLF, «$EndLIBRARY». Что 9.0 делает с именами (FPID), с tedit/timestamps, с uuid (генерирует новые).
Обязательно: возьми фикстуру ${FIX}/legacy_mod/My_lib.mod (модули dip14, mlt, snp8 в deci-mils, из ${REF}/examples/346_8/My_lib.mod) и вручную/скриптом (${SCRATCH}/research/legacy_expected.py) вычисли ОЖИДАЕМЫЙ результат конвертации каждого модуля в мм (таблица: pad номер, тип, форма, x, y, size, drill, layers; тексты; графика) — это станет эталоном для тестов. Подсказка: значения в файле — целые в 1/10000 дюйма: 512 → 1.30048 мм, 315 → 0.8001 мм, 984 → 2.49936 мм (проверь, что современный KiCad даёт именно такие значения с округлением до нм: 512*0.00254=1.30048).
Дополнительно: формат «Units mm» (KiCad 4-5 писали .mod с плавающими мм?) — проверь по legacy plugin, есть ли такая ветка, и опиши. Также: старые файлы с «$MODULE» именем с пробелами, экранирование в Cd. Опиши, какие данные теряются или требуют внимания (Ne, Sc, AR, Op, HOLE-атрибут), и как называть результат (одно .kicad_mod на модуль в каталоге .pretty, имя файла = имя модуля с заменой недопустимых символов — как делает KiCad: FootprintSave / LIB_ID::FixIllegalChars?).`,
  },
  {
    key: 'generators',
    file: 'lab-generators.md',
    prompt: `
ЗАДАЧА: docs/dev/lab-generators.md — «Геометрия типовых корпусов для генераторов kicadfp: лабораторные корпуса dip14/mlt/snp8 и параметрические семейства».
Часть 1 — лабораторные корпуса (эталон приёмки, ТЗ сценарий 5: «площадки 1,3 мм, отверстия 0,8 мм, первая площадка квадратная, шаг и контур соответствуют заданию»). Источники: ${BZR}/kicad-требования-и-задания.md (разделы 1.3б, 1.5, 3.2), ${REF}/kicadgen/gen_footprints.py, ${REF}/kicadgen/mod.py (функции dip/two_pad/pin_rows), ${REF}/examples/346_8.yaml, ${REF}/examples/346_8/My_lib.mod (готовый результат в 1/10000 дюйма — переведи в мм: ×0.00254), ${REF}/docs/workflow.md, ${REF}/docs/conventions.md. Для каждого из dip14, mlt, snp8 дай ПОЛНУЮ спецификацию в мм (ось Y вниз, как KiCad): список площадок (номер, тип thru_hole/np_thru_hole, форма rect/circle, x, y, size, drill, layers), контур шелкографии (отрезки/дуги/окружности с координатами, слой F.SilkS, ширина 0.12 — либо как в исходнике), тексты Reference (F.SilkS) и Value (F.Fab) с позициями и размером шрифта (1×1, толщина 0.15 — современные умолчания; отметь, что в старом формате было 500×500 деци-мил = 1.27 мм), ключ DIP (полукруглая выемка), для snp8 — два монтажных отверстия 3 мм (np_thru_hole, без номера, layers *.Cu *.Mask? — как в стандартной библиотеке MountingHole.pretty: посмотри ${KFP}/v8.0.0/MountingHole.pretty/MountingHole_3.2mm_M3.kicad_mod и Connector_PinHeader… с монтажными отверстиями) и контур 12.5×25 мм. Сетка 1.25 мм. Отметь неоднозначности (нумерация snp8, положение ряда) и принятые решения (по умолчанию как в gen_footprints.py). Приведи ожидаемый результат в виде готовых таблиц, пригодных для assert в тестах.
Часть 2 — параметрические семейства по ТЗ 4.1.3: DIP (pins, pitch, row_pitch), однорядные/двухрядные штыревые разъёмы (rows, cols, pitch, row_pitch, mounting_holes), выводные резисторы и конденсаторы (axial: pitch, body_length, body_diameter; radial: pitch, diameter), диоды (axial с полосой катода), транзисторы с выводами в линию (TO-92 inline: 3 вывода, pitch 1.27/2.54). Извлеки из РЕАЛЬНЫХ файлов стандартной библиотеки ${KFP}/v8.0.0 (Package_DIP.pretty/DIP-14_W7.62mm.kicad_mod, Connector_PinHeader_2.54mm.pretty/PinHeader_1x04_P2.54mm_Vertical.kicad_mod и PinHeader_2x04_P2.54mm_Vertical.kicad_mod, Resistor_THT.pretty/R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal.kicad_mod, Capacitor_THT.pretty/C_Disc_D5.0mm_W2.5mm_P5.00mm.kicad_mod и CP_Radial_D5.0mm_P2.50mm.kicad_mod, Diode_THT.pretty/D_DO-35_SOD27_P7.62mm_Horizontal.kicad_mod, Package_TO_SOT_THT.pretty/TO-92_Inline.kicad_mod — найди точные имена файлов) правила построения: размеры площадок и форм (pad 1 rect/roundrect, остальные oval/circle), drill, положение Reference/Value/${'${REFERENCE}'}, толщины линий (silk 0.12, fab 0.1, courtyard 0.05), отступы courtyard (KLC: 0.25 мм для THT, округление до 0.01), зазор шелкографии от площадок (KLC 0.2 мм от края площадки? 0.11?), fab-контур с скошенным углом ключа (DIP), полукруглая выемка на силке, для конденсаторов полярность (+), для диодов полоса катода; attr through_hole; порядок и состав узлов. Сформулируй для каждого генератора: сигнатуру функции Python (имя, параметры, значения по умолчанию, соответствующие KLC), формулы координат всех элементов, генерируемое имя корпуса по умолчанию (в стиле KiCad: DIP-14_W7.62mm, PinHeader_2x04_P2.54mm_Vertical, R_Axial_..., и лабораторные имена dip14/mlt/snp8 при явном name). Учти пример ТЗ приложения В.2: pin_header(rows=2, cols=4, pitch=2.5, row_pitch=5.0, pad_size=1.3, drill=0.8, first_square=True, mounting_holes=[(11.25,-5.0,3.0),(11.25,15.0,3.0)], name="snp8") — расшифруй систему координат этого примера (где начало, куда идут ряды) и согласуй с Частью 1.`,
  },
]

phase('Research')
log('Запуск 6 исследователей форматов KiCad')
const results = await parallel(TASKS.map(t => () =>
  agent(COMMON + `\nФАЙЛ РЕЗУЛЬТАТА: ${REPO}/docs/dev/${t.file}\n` + t.prompt, { label: 'research:' + t.key, phase: 'Research', effort: 'high', model: 'opus' })
    .then(r => ({ key: t.key, file: t.file, summary: r }))
))

phase('Critique')
const critique = await agent(`Ты — критик полноты. В каталоге ${REPO}/docs/dev/ лежат спецификации форматов KiCad для реализации библиотеки kicadfp (см. техническое задание: чтение/запись .kicad_mod KiCad 6-9 без потерь, модель Footprint/Pad/графика/тексты/model, проверка корректности, генераторы типовых корпусов, CLI, GUI на PySide6, конвертер старого формата .mod). Прочитай ВСЕ файлы docs/dev/*.md целиком. Найди: (1) противоречия между документами (например, разные утверждения о форме токена hide или о кавычках в layers); (2) пробелы — что инженеру понадобится при реализации, но не описано (перечисли конкретно, с указанием, где это можно найти в исходниках ${KSRC} или фикстурах ${FIX}); (3) утверждения без подтверждения (нет ссылки на файл:строку или на фикстуру) — особенно в разделах про порядок токенов и формат чисел; (4) ошибки, которые ты можешь проверить сам за 1-2 минуты (grep по фикстурам, чтение исходника) — проверь и укажи. Ничего в файлах не меняй. Верни структурированный отчёт: список пунктов с полями {doc, severity: high|medium|low, issue, evidence, how_to_fix}. Сводки исследователей для контекста: ${JSON.stringify(results.filter(Boolean).map(r => ({ key: r.key, summary: String(r.summary).slice(0, 1500) })))}`,
  { label: 'critic', phase: 'Critique', effort: 'high', model: 'opus' })

return { results: results.filter(Boolean), critique }